terminal-key: escape

# key-combination: command
# (command is prompted if it starts with a space, otherwise it's run)
key-bindings: {}

show-line-numbers: false
chapter-keyword: CHAPTER
visible-autocompletion-items: 6
spellcheck-active: false
spellcheck-language: en_US
